require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ChatTeamsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ChatTeam. As you add validations to ChatTeam, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChatTeamsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all chat_teams as @chat_teams" do
      chat_team = ChatTeam.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:chat_teams)).to eq([chat_team])
    end
  end

  describe "GET show" do
    it "assigns the requested chat_team as @chat_team" do
      chat_team = ChatTeam.create! valid_attributes
      get :show, {:id => chat_team.to_param}, valid_session
      expect(assigns(:chat_team)).to eq(chat_team)
    end
  end

  describe "GET new" do
    it "assigns a new chat_team as @chat_team" do
      get :new, {}, valid_session
      expect(assigns(:chat_team)).to be_a_new(ChatTeam)
    end
  end

  describe "GET edit" do
    it "assigns the requested chat_team as @chat_team" do
      chat_team = ChatTeam.create! valid_attributes
      get :edit, {:id => chat_team.to_param}, valid_session
      expect(assigns(:chat_team)).to eq(chat_team)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChatTeam" do
        expect {
          post :create, {:chat_team => valid_attributes}, valid_session
        }.to change(ChatTeam, :count).by(1)
      end

      it "assigns a newly created chat_team as @chat_team" do
        post :create, {:chat_team => valid_attributes}, valid_session
        expect(assigns(:chat_team)).to be_a(ChatTeam)
        expect(assigns(:chat_team)).to be_persisted
      end

      it "redirects to the created chat_team" do
        post :create, {:chat_team => valid_attributes}, valid_session
        expect(response).to redirect_to(ChatTeam.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chat_team as @chat_team" do
        post :create, {:chat_team => invalid_attributes}, valid_session
        expect(assigns(:chat_team)).to be_a_new(ChatTeam)
      end

      it "re-renders the 'new' template" do
        post :create, {:chat_team => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chat_team" do
        chat_team = ChatTeam.create! valid_attributes
        put :update, {:id => chat_team.to_param, :chat_team => new_attributes}, valid_session
        chat_team.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested chat_team as @chat_team" do
        chat_team = ChatTeam.create! valid_attributes
        put :update, {:id => chat_team.to_param, :chat_team => valid_attributes}, valid_session
        expect(assigns(:chat_team)).to eq(chat_team)
      end

      it "redirects to the chat_team" do
        chat_team = ChatTeam.create! valid_attributes
        put :update, {:id => chat_team.to_param, :chat_team => valid_attributes}, valid_session
        expect(response).to redirect_to(chat_team)
      end
    end

    describe "with invalid params" do
      it "assigns the chat_team as @chat_team" do
        chat_team = ChatTeam.create! valid_attributes
        put :update, {:id => chat_team.to_param, :chat_team => invalid_attributes}, valid_session
        expect(assigns(:chat_team)).to eq(chat_team)
      end

      it "re-renders the 'edit' template" do
        chat_team = ChatTeam.create! valid_attributes
        put :update, {:id => chat_team.to_param, :chat_team => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chat_team" do
      chat_team = ChatTeam.create! valid_attributes
      expect {
        delete :destroy, {:id => chat_team.to_param}, valid_session
      }.to change(ChatTeam, :count).by(-1)
    end

    it "redirects to the chat_teams list" do
      chat_team = ChatTeam.create! valid_attributes
      delete :destroy, {:id => chat_team.to_param}, valid_session
      expect(response).to redirect_to(chat_teams_url)
    end
  end

end
